AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AwsWhatsNew:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handler.lambda_handler
      CodeUri: ./
      Timeout: 200
      Environment:
        Variables:
          bucket: !Ref AwsNewsBucket
          PostsTableName: !Ref AwsNewsRecentPostsTable
      Events:
        CheckForNewPostsScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AwsNewsRecentPostsTable
        - Statement:
          -
            Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource:
              Fn::GetAtt:
                - "SecretsKey"
                - "Arn"
          -
            Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource:
              !Join ['', ['arn:aws:s3:::', !Ref AwsNewsBucket, '/secrets.json']]
          -
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource:
              !Join ['', ['arn:aws:s3:::', !Ref AwsNewsBucket, '/news.rss']]
  AwsNewsBucket:
    Type: AWS::S3::Bucket
  AwsNewsRecentPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: guid
          AttributeType: S
      KeySchema:
        - AttributeName: guid
          KeyType: HASH
  SecretsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          -
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal: 
              AWS: 
                - "arn:aws:iam::099765626945:root"
                - "arn:aws:iam::099765626945:user/andrew_dilosa"
                - "arn:aws:iam::099765626945:user/AndrewsMacbookPro"
            Action: "kms:*"
            Resource: "*"

